### ISSUE TITLE
Nodes become unreported 2 hours after last submitted report.

### ISSUE THREAD

**Issue by sheijmans** [propyless/panopuppet#136]
Nodes become unreported 2 hours after last submitted report also when specifying PUPPET_RUN_INTERVAL with a longer time.

```
Latest Report
2016-04-28 21:09:31

Thu Apr 28 22:57:24 CEST 2016
{
  "avg_resource": "351.86",
  "failed_nodes": 0,
  "total_resource": 2463,
  "unreported_nodes": 6,
  "pending_nodes": 0,
  "population": 7,
  "changed_nodes": 0,
  "mismatching_timestamps": 0
}Thu Apr 28 23:12:24 CEST 2016
{
  "avg_resource": "351.86",
  "failed_nodes": 0,
  "total_resource": 2463,
  "unreported_nodes": 7,
  "pending_nodes": 0,
  "population": 7,
  "changed_nodes": 0,
  "mismatching_timestamps": 0
}
```

**Comment by propyless** [comment]
https://github.com/propyless/panopuppet/blob/dev/panopuppet/pano/puppetdb/pdbutils.py#L45
https://github.com/propyless/panopuppet/blob/dev/panopuppet/pano/methods/dictfuncs.py#L143

Thanks for reporting your findings! The problem seems to be that I never send the run_time_interval replacing the default of "2" hours.

**Comment by propyless** [comment]
Fix has been pushed to Dev
