### ISSUE TITLE
Automatic logout after timeout

### ISSUE THREAD

**Issue by emahags** [propyless/panopuppet#66]
There is no indication that your session has timed out. If you for example do a search, it will stay on "Fetching data from puppetdb" indefinitely.

**Comment by propyless** [comment]
Okay.. I've got a solution where upon search/refresh it will check if the api call got redirected to the login page. If that happens it will open a new tab to the login page.
this is so that the query (if there was one) will not be reset.

Would you be happy with that?

**Comment by propyless** [comment]
Oh.. after you have logged in it will also close the tab.

**Comment by emahags** [comment]
This feels a bit clunky compared to how it's usually handled (save the destination and redirect there after login), but I guess it's better than nothing.

**Comment by propyless** [comment]
Ok, i've got another solution I can try then :)

**Comment by propyless** [comment]
Hi the latest changes...
Now upon searching after being logged out, it will redirect you to the login page
and send you back to the nodes page with the query you entered into the query builder.

Does that sounds all right?

**Comment by emahags** [comment]
That sounds better, but a bit specific. What happens if you're for example jumping around in Analytics when you get logged out?

**Comment by propyless** [comment]
Ah, no its only the nodes page which needs this implementation.
the other pages all follow links so if you were to be logged out, the django login middleware would automatically  redirect you back to the link you clicked on once you've logged in.

What happens on the nodes page when you press search is that a api call is made, that api call however gets redirected to the login page but since the jscript did not handle if that occurred it went never reached the code that closes the loading modal.

The code I added in this PR checks if the api call was redirected and if that happened it would try to generate a puppetdb query from the search form if one was created, if successful it will send that query to the login page with the param ?next=pano/nodes/?load_query=["awesome","query","here"]
So after login you it would redirect you to the nodes page.

**Comment by emahags** [comment]
Sounds great!

**Comment by propyless** [comment]
fixed in pr #74
